version: 2
jobs:
  build:
    working_directory: ~/capacity-api
    docker:
      - image: circleci/python:3.6.1
        environment:
          DATABASE_URL: postgres://root:@127.0.0.1:5432/circle_test
          REDIS_URL: rediscache://redis:6379/1?client_class=django_redis.client.DefaultClient
          CELERY_BROKER_URL: amqp://admin:password@rabbitmq:5672//
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd api
            python manage.py test --settings=config.settings_test
      - store_artifacts:
          path: test-reports/
          destination: tr1
